scan_timeout = 10
format = "[# ${custom.git_repo_name}$all](dimmed)"

[character]  # The name of the module we are configuring is "character"
success_symbol = "[;](bold green)"  # The "success_symbol" segment is being set to ";" with the color "bold green"
error_symbol = "[;](bold red)"

[aws]
symbol = "  "

[conda]
symbol = " "

[dart]
symbol = " "

[directory]
read_only = " "

[docker_context]
symbol = " "

[elixir]
symbol = " "

[elm]
symbol = " "

[git_branch]
symbol = " "

[golang]
symbol = " "

[hostname]
ssh_symbol = "🌐 "

[hg_branch]
symbol = " "

[java]
symbol = " "

[julia]
symbol = " "

[memory_usage]
symbol = " "

[nim]
symbol = " "

[nix_shell]
symbol = " "

[nodejs]
format = "[$symbol($version)]($style) "

[package]
symbol = " "

[perl]
symbol = " "

[php]
symbol = " "

[python]
symbol = " "

[ruby]
symbol = " "

# https://starship.rs/config/#r
[rlang]
symbol = "R "

[rust]
symbol = " "

[scala]
symbol = " "

[shlvl]
symbol = " "

[swift]
symbol = "ﯣ "

[kubernetes]
symbol = "☸ "
disabled = false

[git_metrics]
disabled = false

[custom.git_repo_name]
command = "~/bin/git-repo-name || true"
format = "[$output](bold green)/"
when = true
require_repo = true
